import os
import json
from dotenv import load_dotenv
from supabase import create_client, Client

# Load cloud credentials
load_dotenv('backend/.env')

URL = os.getenv("SUPABASE_URL")
KEY = os.getenv("SUPABASE_KEY")
KNOWLEDGE_PATH = "backend/app/data/medicinal_knowledge.json"

if not URL or not KEY:
    print(">>> ERROR: Supabase credentials missing in .env")
    exit(1)

supabase: Client = create_client(URL, KEY)

def sync_data():
    print(f">>> SYNC START: Connecting to {URL}...")
    
    # 1. Load local knowledge
    try:
        with open(KNOWLEDGE_PATH, encoding='utf-8') as f:
            kb = json.load(f)
    except Exception as e:
        print(f">>> ERROR: Failed to read local knowledge: {e}")
        return

    print(f">>> DATA LOADED: Found {len(kb)} monographs.")

    # 2. Prepare data for Supabase
    # We will store the full JSON in a column or flatten it. 
    # For the Neural HUD, a flat structure with a JSON blob for metadata is ideal.
    
    records = []
    for species, data in kb.items():
        records.append({
            "scientific_name": species,
            "common_names": data.get("common_names", []),
            "family": data.get("family", "Unknown"),
            "ayurvedic_uses": data.get("ayurvedic_uses", []),
            "preparation": data.get("preparation", ""),
            "active_compounds": data.get("active_compounds", []),
            "toxicity_level": data.get("toxicity", {}).get("level", "unknown"),
            "full_profile": data # Store full JSON for future-proofing
        })

    # 3. Upsert to Supabase
    # Note: This assumes a table named 'medicinal_plants' exists. 
    # In a real scenario, we might need to create it via SQL first.
    try:
        print(">>> UPLOADING: Synchronizing records to cloud...")
        # We chunk this to avoid timeout
        for i in range(0, len(records), 10):
            chunk = records[i:i+10]
            # Use scientific_name as unique identifier
            response = supabase.table("medicinal_plants").upsert(chunk, on_conflict="scientific_name").execute()
            print(f"  Processed {min(i+10, len(records))}/{len(records)} records...")
        
        print(">>> SUCCESS: Botanical Intelligence is now LIVE in the cloud.")
    except Exception as e:
        print(f">>> DATABASE ERROR: {e}")
        print("\n>>> IMPORTANT: Ensure you have created the 'medicinal_plants' table in your Supabase dashboard.")
        print(">>> SQL to run in Supabase SQL Editor:")
        print("""
        CREATE TABLE IF NOT EXISTS medicinal_plants (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            scientific_name TEXT UNIQUE NOT NULL,
            common_names TEXT[] DEFAULT '{}',
            family TEXT,
            ayurvedic_uses TEXT[] DEFAULT '{}',
            preparation TEXT,
            active_compounds TEXT[] DEFAULT '{}',
            toxicity_level TEXT,
            full_profile JSONB
        );
        """)

if __name__ == "__main__":
    sync_data()
