import os
import json
from dotenv import load_dotenv
from supabase import create_client, Client

# Load cloud credentials
load_dotenv('backend/.env')

URL = os.getenv("SUPABASE_URL")
KEY = os.getenv("SUPABASE_KEY")
KNOWLEDGE_PATH = "backend/app/data/medicinal_knowledge.json"

if not URL or not KEY:
    print(">>> ERROR: Supabase credentials missing in .env")
    exit(1)

supabase: Client = create_client(URL, KEY)

def sync_data():
    print(f">>> SYNC START: Connecting to {URL}...")
    
    # 1. Load local knowledge
    try:
        with open(KNOWLEDGE_PATH, encoding='utf-8') as f:
            kb = json.load(f)
    except Exception as e:
        print(f">>> ERROR: Failed to read local knowledge: {e}")
        return

    print(f">>> DATA LOADED: Found {len(kb)} monographs.")

    # 2. Prepare data for Supabase
    # We will store the full JSON in a column or flatten it. 
    # For the Neural HUD, a flat structure with a JSON blob for metadata is ideal.
    
    records = []
    for species, data in kb.items():
        # Curated "WOW" fallback for common names
        search_term = data.get("common_names", [species])[0]
        image_url = f"https://images.unsplash.com/photo-1596755094514-f87e34085b2c?q=80&w=2670&auto=format&fit=crop&q=plant,{search_term}"
        
        records.append({
            "scientific_name": species,
            "common_names": data.get("common_names", []),
            "family": data.get("family", "Unknown"),
            "ayurvedic_uses": data.get("ayurvedic_uses", []),
            "preparation": data.get("preparation", ""),
            "active_compounds": data.get("active_compounds", []),
            "toxicity_level": data.get("toxicity", {}).get("level", "unknown"),
            "image_url": image_url, # New high-quality visual
            "full_profile": data 
        })

    # 3. Upsert to Supabase
    try:
        print(">>> UPLOADING: Synchronizing records to cloud...")
        for i in range(0, len(records), 10):
            chunk = records[i:i+10]
            # Try with image_url first
            try:
                supabase.table("medicinal_plants").upsert(chunk, on_conflict="scientific_name").execute()
            except Exception:
                # Fallback: Remove image_url and try again
                for r in chunk: r.pop("image_url", None)
                supabase.table("medicinal_plants").upsert(chunk, on_conflict="scientific_name").execute()
            print(f"  Processed {min(i+10, len(records))}/{len(records)} records...")
        
        print(">>> SUCCESS: Botanical Intelligence is now LIVE.")
    except Exception as e:
        print(f">>> DATABASE ERROR: {e}")
        print("\n>>> SQL to run in Supabase SQL Editor (to support images):")
        print("""
        CREATE TABLE IF NOT EXISTS medicinal_plants (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            scientific_name TEXT UNIQUE NOT NULL,
            common_names TEXT[] DEFAULT '{}',
            family TEXT,
            ayurvedic_uses TEXT[] DEFAULT '{}',
            preparation TEXT,
            active_compounds TEXT[] DEFAULT '{}',
            toxicity_level TEXT,
            image_url TEXT,
            full_profile JSONB
        );
        -- If table exists, just add the column:
        -- ALTER TABLE medicinal_plants ADD COLUMN IF NOT EXISTS image_url TEXT;
        """)

if __name__ == "__main__":
    sync_data()
