"""
Run once to create tables and seed all 81 plants in Supabase.
Safe to run multiple times — uses IF NOT EXISTS and upsert.
"""
import os, sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import create_engine, text

# Default for migration if env not set
DATABASE_URL = os.environ.get("DATABASE_URL")
if not DATABASE_URL:
    raise ValueError("DATABASE_URL environment variable is not set")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql://", 1)

engine = create_engine(DATABASE_URL, connect_args={"sslmode": "require"})

CREATE_TABLE = """
CREATE TABLE IF NOT EXISTS plants (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    scientific_name VARCHAR(255),
    family VARCHAR(255),
    ayurvedic_name VARCHAR(255),
    medicinal_uses TEXT,
    parts_used VARCHAR(255),
    preparation TEXT,
    active_compounds TEXT,
    toxicity TEXT,
    description TEXT,
    habitat VARCHAR(255),
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);
"""

PLANTS_DATA = [
    ("Aloevera","Aloe barbadensis miller","Asphodelaceae","Kumari","Burns, wound healing, digestive disorders, anti-inflammatory, skin conditions","Leaf gel, latex","Gel applied topically; juice 20ml twice daily","Aloin, acemannan, anthraquinones, vitamins A C E","Gel safe externally; latex avoid prolonged use","Succulent plant with powerful healing gel used worldwide","Arid regions, widely cultivated"),
    ("Amla","Phyllanthus emblica","Phyllanthaceae","Amalaki","Vitamin C powerhouse, hair growth, immunity, digestion, anti-aging, liver protection","Fruit, leaves, bark, seeds","Raw fruit, juice, churna powder, hair oil","Emblicanin A and B, ascorbic acid, gallic acid, ellagic acid","Non-toxic; safe for all ages","Contains as much Vitamin C as 20 oranges — heat stable due to protective tannins","Tropical and subtropical India"),
    ("Amruthaballi","Tinospora cordifolia","Menispermaceae","Guduchi","Immune booster, antipyretic, anti-diabetic, antioxidant, liver protection, arthritis","Stem, roots, leaves","Stem decoction, powder, juice, kadha","Tinosporine, berberine, tinosporic acid, cordifolide","Safe; monitor blood sugar if diabetic","Called Amrita — nectar of immortality in Sanskrit","Tropical India, Myanmar, Sri Lanka"),
    ("Arali","Nerium oleander","Apocynaceae","Karaveera","Skin diseases, wound healing, anti-inflammatory externally","Leaves, bark, roots","External application only — paste","Oleandrin, neriine, digitoxigenin","TOXIC — all parts toxic if ingested; external use only","Ornamental plant with significant toxicity — handle with care","Mediterranean, South Asia"),
    ("Astma_weed","Euphorbia hirta","Euphorbiaceae","Dudhi","Asthma, bronchitis, cough, dysentery, worm infections","Whole plant, leaves","Decoction, fresh juice","Quercitrin, myricitrin, euphorbin, shikimic acid","Milky latex causes skin irritation; avoid in pregnancy","Traditional remedy for respiratory disorders across Asia and Africa","Tropical and subtropical regions worldwide"),
    ("Badipala","Wrightia tinctoria","Apocynaceae","Kutaja","Skin diseases, psoriasis, anti-inflammatory, diarrhea","Leaves, bark, seeds","Leaf paste, bark decoction, seed oil","Wrightine, norchelerythrine, indirubin","Generally safe in therapeutic doses","Leaves used to make traditional indigo dye and medicine simultaneously","Tropical India and Sri Lanka"),
    ("Balloon_Vine","Cardiospermum halicacabum","Sapindaceae","Jyotishmati","Joint pain, rheumatism, skin diseases, hair growth, anti-inflammatory","Leaves, roots, seeds","Leaf paste, decoction, hair oil","Luteolin, chrysoeriol, apigenin, procyanidins","Generally safe; avoid in pregnancy","Climbing vine whose balloon-like seed pods give it its name","Tropical Americas, Asia, Africa"),
    ("Bamboo","Bambusa vulgaris","Poaceae","Vanshalochan","Respiratory disorders, wound healing, fever, digestive disorders","Young shoots, leaves, stem","Decoction, fresh shoots in diet","Silica, flavonoids, phenolic acids, lignans","Generally safe; young shoots edible","Fastest growing plant on Earth — some species grow 91cm per day","Tropical and subtropical Asia"),
    ("Beans","Phaseolus vulgaris","Fabaceae","Rajmasha","Diabetes management, heart health, digestive health, protein source","Seeds, pods, leaves","Cooked seeds, pod decoction","Lectins, phaseolin, quercetin, kaempferol","Raw beans toxic due to lectins — always cook thoroughly","One of the most important food crops globally, cultivated for 7000+ years","Tropical Americas, widely cultivated"),
    ("Betel","Piper betle","Piperaceae","Tambula","Digestive aid, oral health, antibacterial, wound healing, respiratory","Leaves","Fresh leaves chewed, paste","Chavibetol, eugenol, allylpyrocatechol, hydroxychavicol","Habitual chewing with tobacco causes oral cancer — leaf alone is safer","Sacred plant in Hindu rituals — offered to deities for 3000+ years","South and Southeast Asia"),
    ("Bhrami","Bacopa monnieri","Plantaginaceae","Brahmi","Memory, cognitive function, anxiety, ADHD, neuroprotection, epilepsy","Whole plant","Fresh juice, powder, ghee infusion","Bacosides A and B, brahmine, herpestine, alkaloids","Safe; nausea on empty stomach; avoid in hypothyroidism","NASA studied Brahmi for astronauts due to cognitive stress reduction","Wetlands throughout India and Southeast Asia"),
    ("Bringaraja","Eclipta prostrata","Asteraceae","Bhringaraja","Hair growth, liver protection, anti-inflammatory, wound healing, jaundice","Whole plant, leaves","Fresh juice, oil, powder","Wedelolactone, ecliptine, eclalbatin, coumestans","Generally safe in therapeutic doses","Called Kesharaj — king of hair — in Ayurveda","Moist and marshy areas worldwide"),
    ("Caricature","Graptophyllum pictum","Acanthaceae","Chitraparna","Hemorrhoids, skin diseases, constipation, wound healing","Leaves, bark","Leaf paste, decoction","Alkaloids, flavonoids, tannins, anthocyanins","Generally safe in traditional doses","Ornamental shrub with striking variegated leaves used medicinally","Tropical Pacific Islands and Southeast Asia"),
    ("Castor","Ricinus communis","Euphorbiaceae","Eranda","Joint pain, constipation, skin disorders, anti-inflammatory","Seeds, leaves, roots, oil","Castor oil, leaf poultice","Ricinoleic acid, ricinine, ricin","Seeds contain ricin — one of most toxic natural substances; oil is safe","Castor oil is one of the oldest cultivated crops — 6000 years of use","Tropical Africa, widely naturalized"),
    ("Catharanthus","Catharanthus roseus","Apocynaceae","Sadabahar","Diabetes, hypertension, anti-cancer, wound healing","Leaves, flowers, roots","Decoction, fresh leaf juice","Vincristine, vinblastine, ajmalicine, catharanthine","Contains powerful alkaloids — vincristine used in cancer chemotherapy","Source of two major cancer drugs — vincristine and vinblastine","Madagascar, widely cultivated tropically"),
    ("Chakte","Caesalpinia sappan","Fabaceae","Patanga","Blood disorders, anti-inflammatory, wound healing, dysmenorrhea","Heartwood, bark","Decoction, powder","Brazilin, brazilein, sappanchalcone, haematoxylin","Avoid in pregnancy and bleeding disorders","Used as natural red dye for centuries alongside medicinal use","Southeast Asia, India"),
    ("Chilly","Capsicum annuum","Solanaceae","Maricha","Pain relief, digestion, metabolism, anti-inflammatory, cardiovascular","Fruits","Fresh, dried, powder, capsaicin extract","Capsaicin, capsanthin, dihydrocapsaicin, vitamin C","Causes intense burning — avoid in gastric ulcers and acid reflux","Capsaicin tricks the brain into feeling heat — used in pain patches","Americas, widely cultivated globally"),
    ("Citron lime","Citrus medica","Rutaceae","Bijapura","Digestive disorders, liver conditions, respiratory, antiseptic, vitamin C","Fruit, peel, juice, leaves","Fresh juice, peel decoction, essential oil","Hesperidin, eriocitrin, limonene, vitamin C","Generally safe; acidic — avoid in tooth enamel issues","One of the original citrus fruits from which all modern citrus evolved","Northeast India, widely cultivated"),
    ("Coffee","Coffea arabica","Rubiaceae","Kapi","Mental alertness, fatigue, headaches, antioxidant, liver protection","Seeds (beans), leaves","Decoction, brew","Caffeine, chlorogenic acid, cafestol, kahweol","Excess causes anxiety, insomnia, hypertension; addictive","Coffee was discovered when Ethiopian goats were seen dancing after eating berries","Ethiopia, widely cultivated tropically"),
    ("Common_rue","Ruta graveolens","Rutaceae","Sadap","Menstrual disorders, anti-spasmodic, antimicrobial, eye disorders","Leaves, flowers","Infusion, fresh juice, essential oil","Rutin, bergapten, xanthotoxin, graveoline","TOXIC in large doses; causes abortion; avoid in pregnancy completely","Used in ancient Rome and Greece as medicine, flavoring, and insect repellent","Mediterranean, Southern Europe"),
    ("Curry_Leaf","Murraya koenigii","Rutaceae","Meetha Neem","Diabetes, hair loss, digestion, cholesterol, antioxidant, antibacterial","Leaves, bark, roots","Fresh leaves in food, decoction, hair oil","Mahanimbine, carbazole alkaloids, koenigine, murrayanol","Non-toxic; safe for all ages","Essential in South Indian cuisine — alkaloids proven to lower blood sugar","South India, Sri Lanka"),
    ("Drumstick","Moringa oleifera","Moringaceae","Shigru","Malnutrition, anti-inflammatory, blood sugar, antioxidant, lactation","Leaves, seeds, pods, roots, bark","Leaf powder, fresh leaves cooked, seed oil","Isothiocyanates, quercetin, chlorogenic acid, zeatin","Leaves and pods safe; root bark toxic — avoid","Leaves contain 7x Vitamin C of oranges and 4x calcium of milk","Foothills of Himalayas, widely cultivated"),
    ("Ekka","Calotropis gigantea","Apocynaceae","Arka","Skin diseases, pain, anti-inflammatory, digestive, respiratory","Latex, leaves, bark, roots","External paste, bark decoction","Calotropin, uscharin, calactin, gigantin","TOXIC internally — latex causes severe irritation; medicinal use requires expertise","Used in funeral pyres in Hinduism — flowers offered to Lord Shiva","South and Southeast Asia, Africa"),
    ("Eucalyptus","Eucalyptus globulus","Myrtaceae","Tailparna","Respiratory infections, decongestant, antibacterial, fever, muscle pain","Leaves, essential oil","Steam inhalation, essential oil, decoction","Eucalyptol, alpha-pinene, limonene, aromadendrene","Essential oil toxic if ingested undiluted; avoid near infants","Eucalyptus forests cover 1% of Earth's reforested land — fastest growing timber tree","Australia, widely planted globally"),
    ("Ganike","Solanum nigrum","Solanaceae","Kakamachi","Liver disorders, fever, anti-inflammatory, skin diseases, diuretic","Berries, leaves, roots","Berry juice, leaf decoction","Solanine, solasonine, chaconine, solamargine","Unripe berries toxic — solanine causes poisoning; ripe berries safer","Controversial plant — toxic when unripe, used as medicine and food when ripe","Worldwide weed distribution"),
    ("Gauva","Psidium guajava","Myrtaceae","Amrood","Diarrhea, dysentery, anti-diabetic, anti-inflammatory, cough, wound healing","Leaves, fruit, bark","Leaf decoction, fresh fruit, bark infusion","Quercetin, guaijaverin, leucocyanidin, vitamin C","Generally safe; very high in Vitamin C","Guava leaves kill antibiotic-resistant bacteria — documented in multiple clinical studies","Tropical Americas, widely cultivated"),
    ("Geranium","Pelargonium graveolens","Geraniaceae","Rosha","Anxiety, skin care, anti-inflammatory, antifungal, wound healing","Leaves, essential oil","Essential oil, infusion, topical application","Geraniol, citronellol, linalool, rose oxide","Generally safe topically; avoid undiluted essential oil on sensitive skin","Rose geranium essential oil is used as a natural mosquito repellent","South Africa, widely cultivated"),
    ("Ginger","Zingiber officinale","Zingiberaceae","Shunthi","Nausea, digestion, anti-inflammatory, cold and flu, pain relief, circulation","Rhizome","Fresh juice, decoction, powder, tea","Gingerols, shogaols, paradols, zingerone","Safe in food amounts; high doses cause heartburn; caution with blood thinners","Used for 5000 years across every major traditional medicine system in the world","South Asia, widely cultivated tropically"),
    ("Globe Amarnath","Gomphrena globosa","Amaranthaceae","Makhamali","Respiratory disorders, fever, urinary disorders, anti-inflammatory","Flowers, whole plant","Flower infusion, decoction","Gomphrenin, betacyanins, flavonoids, betaine","Generally safe in traditional doses","Flowers retain their color for years when dried — used in eternal bouquets","Tropical Americas, widely cultivated"),
    ("Henna","Lawsonia inermis","Lythraceae","Mehndi","Skin conditions, fever, headache, anti-inflammatory, wound healing","Leaves, bark, seeds, flowers","Leaf paste for skin, decoction","Lawsone, gallic acid, glucose, mannitol","Generally safe; black henna contains PPD — causes severe allergic reactions","Used for body art for 5000+ years — oldest cosmetic plant known to history","Middle East, South Asia, North Africa"),
    ("Hibiscus","Hibiscus rosa-sinensis","Malvaceae","Japa","Blood pressure, hair growth, liver protection, anti-inflammatory, cholesterol","Flowers, leaves, roots","Flower tea, hair oil, paste","Anthocyanins, hibiscin, quercetin, vitamin C","Generally safe; avoid high doses in pregnancy","Hibiscus tea lowers blood pressure as effectively as some medications in studies","Tropical Asia, widely cultivated"),
    ("Honge","Millettia pinnata","Fabaceae","Karanja","Skin diseases, wound healing, anti-inflammatory, rheumatism, antibacterial","Seeds, leaves, bark, oil","Seed oil, bark paste, leaf decoction","Karanjin, pongamol, kanjone, flavonoids","Toxic if ingested; external use only; seed oil for skin","Seeds contain up to 40% oil used as biodiesel — a sustainable energy crop","South and Southeast Asia"),
    ("Insulin","Costus pictus","Costaceae","Insulin plant","Diabetes management, blood sugar reduction, anti-inflammatory","Leaves","Fresh leaves chewed daily; decoction","Diosgenin, quercetin, kaempferol, insulin-like peptides","Generally safe; monitor blood sugar closely if diabetic","Chewing one leaf daily shown to reduce blood sugar in multiple Indian studies","Tropical Americas, cultivated in India"),
    ("Jackfruit","Artocarpus heterophyllus","Moraceae","Panasa","Anti-diabetic, anti-inflammatory, wound healing, digestive, antioxidant","Leaves, seeds, bark, fruit","Leaf decoction, seed powder, fresh fruit","Artocarpanone, morusin, cycloartocarpin, jacalin lectin","Generally safe; latex may cause allergy in latex-sensitive individuals","Largest fruit in the world — a single fruit can weigh up to 55 kg","South India, Bangladesh, widely cultivated"),
    ("Jasmine","Jasminum officinale","Oleaceae","Mallika","Anxiety, depression, antiseptic, liver disorders, skin care","Flowers, leaves","Essential oil, flower infusion, paste","Jasmone, benzyl acetate, linalool, indole","Generally safe; essential oil very concentrated — dilute before use","Jasmine is the national flower of Pakistan, Indonesia, and Philippines","South Asia, widely cultivated"),
    ("Kambajala","Prosopis juliflora","Fabaceae","Vilayati Babool","Antimicrobial, wound healing, digestive, tooth care","Bark, pods, leaves","Bark decoction, fresh pod chewing, leaf infusion","Julifloridine, prosopinine, prolamine, alkaloids","Invasive species; excess causes neurological issues in livestock","Introduced from Americas — now considered an invasive weed across Indian drylands","Americas, naturalized globally"),
    ("Kasambramu","Croton bonplandianum","Euphorbiaceae","Ban Tulsi","Wound healing, skin diseases, anti-inflammatory, fever","Leaves, seeds, bark","Leaf paste, seed oil","Croton oil, diterpenes, flavonoids, tannins","Croton oil is a powerful laxative and irritant — handle carefully","Common roadside weed with significant antimicrobial activity against resistant bacteria","Tropical Americas, naturalized in India"),
    ("Kohlrabi","Brassica oleracea","Brassicaceae","Nava Komal Shak","Digestive health, anti-inflammatory, antioxidant, metabolism, cancer prevention","Bulb, leaves","Raw or cooked as vegetable, juice","Glucosinolates, vitamin C, potassium, fiber, anthocyanins","Generally safe; excessive intake may affect thyroid in iodine deficiency","A vegetable that looks like a spaceship — entirely edible including leaves and stems","Northern Europe, widely cultivated"),
    ("Lantana","Lantana camara","Verbenaceae","Raimuniya","Skin diseases, respiratory disorders, wound healing, anti-inflammatory","Leaves, flowers, roots","External paste, leaf infusion","Lantanene A and B, oleanolic acid, ursolic acid, lantadene","TOXIC — berries highly toxic especially to children; all parts potentially toxic","Considered one of 100 worst invasive species globally — yet used in traditional medicine","Tropical Americas, invasive worldwide"),
    ("Lemon","Citrus limon","Rutaceae","Nimbu","Vitamin C, digestion, immune support, weight management, antibacterial","Fruit, peel, juice, leaves","Fresh juice, peel infusion, essential oil","Limonene, hesperidin, eriocitrin, vitamin C","Generally safe; acidic — dilute juice; avoid on tooth enamel directly","A single lemon contains enough vitamin C for a full day's requirement","Northeast India and China, widely cultivated"),
    ("Lemongrass","Cymbopogon citratus","Poaceae","Bhustrina","Anxiety, fever, pain relief, antifungal, antibacterial, cholesterol, detox","Stems, leaves, essential oil","Tea, essential oil diffusion, decoction","Citral, geraniol, limonene, myrcene, linalool","Safe as tea; essential oil toxic if ingested; avoid in pregnancy","Lemongrass essential oil is one of the most potent natural antifungal agents known","Southeast Asia, tropical cultivation"),
    ("Malabar_Nut","Adhatoda vasica","Acanthaceae","Vasa","Respiratory disorders, asthma, bronchitis, cough, expectorant","Leaves, roots, flowers, bark","Leaf decoction, fresh juice, powder","Vasicine, vasicinone, deoxyvasicine, adhatodine","Avoid in pregnancy — causes uterine contractions; abortifacient in large doses","Vasicine from Malabar nut is the source of the synthetic drug bromhexine","South Asia, Southeast Asia"),
    ("Mango","Mangifera indica","Anacardiaceae","Amra","Digestive disorders, diarrhea, fever, skin conditions, antioxidant","Leaves, bark, seed kernel, flowers","Leaf infusion, bark decoction, seed kernel powder","Mangiferin, quercetin, gallic acid, vitamin C and A","Mango latex causes contact dermatitis in sensitive individuals","India's national fruit — cultivated for over 4000 years; 1000+ varieties exist","South Asia, widely cultivated tropically"),
    ("Marigold","Tagetes erecta","Asteraceae","Genda","Wound healing, anti-inflammatory, antibacterial, skin conditions, eye health","Flowers, leaves","Flower infusion, topical paste, eye wash","Lutein, zeaxanthin, quercetin, patuletin, limonene","Generally safe; may cause allergic reaction in ragweed-sensitive individuals","Lutein from marigold is used in eye supplements — protects against macular degeneration","Mexico, widely cultivated globally"),
    ("Mint","Mentha arvensis","Lamiaceae","Pudina","Digestion, IBS, headache, nausea, decongestant, antibacterial","Leaves, essential oil","Tea, fresh leaves, essential oil, capsules","Menthol, menthone, pulegone, isomenthone","Safe as food; hish doses cause heartburn; avoid in kidney disease","Mint is the world's most commercially grown herb by volume","Europe, Asia, widely cultivated"),
    ("Neem","Azadirachta indica","Meliaceae","Nimba","Antibacterial, antifungal, antiviral, blood purifier, skin diseases, dental hygiene","Leaves, bark, seeds, oil, roots","Leaf paste, decoction, oil, twig as toothbrush","Nimbin, nimbidin, azadirachtin, quercetin, limonoids","Safe medicinally; seed oil toxic in high doses; avoid in pregnancy","Every part of neem has medicinal value — referenced as sarva roga nivarini meaning curer of all ailments","Tropical South Asia"),
    ("Nelavembu","Andrographis paniculata","Acanthaceae","Kalmegh","Fever, liver disorders, anti-inflammatory, immune support, malaria","Leaves, whole plant","Decoction, powder, juice","Andrographolide, neoandrographolide, 14-deoxyandrographolide","Very bitter; high doses cause gastric irritation; avoid in pregnancy","Called King of Bitters — one of the most bitter plants used medicinally in Ayurveda","South and Southeast Asia"),
    ("Nerale","Syzygium cumini","Myrtaceae","Jamun","Diabetes, digestive disorders, liver, anti-inflammatory, blood pressure","Fruit, seeds, bark, leaves","Seed powder, bark decoction, fresh fruit","Jamboline, anthocyanins, ellagic acid, gallic acid","Generally safe; excessive fruit may cause sore throat and fever","Jamun seeds contain jamboline which blocks starch conversion to sugar — potent anti-diabetic","South Asia, widely cultivated"),
    ("Nooni","Morinda citrifolia","Rubiaceae","Ashyuka","Immune support, pain relief, anti-inflammatory, antioxidant, energy","Fruit, leaves, roots, bark","Fruit juice, leaf poultice, root decoction","Xeronine, damnacanthal, scopoletin, rutin","High potassium content — avoid in kidney disease; possible liver toxicity in excess","Noni fruit juice has been studied in 1000+ research papers for its broad medicinal activity","Polynesia, Southeast Asia, widely cultivated"),
    ("Onion","Allium cepa","Amaryllidaceae","Palandu","Anti-inflammatory, blood pressure, cholesterol, blood sugar, antibacterial, immune","Bulb, leaves","Raw, cooked, juice, poultice","Quercetin, allicin, alliin, sulfur compounds","Generally safe; causes heartburn in excess; anticoagulant effect","Onions have been used as medicine and food for 7000+ years — found in ancient Egyptian tombs","Central Asia, cultivated globally for millennia"),
    ("Pappaya","Carica papaya","Caricaceae","Papita","Digestive health, anti-parasitic, wound healing, dengue fever, anti-inflammatory","Fruit, leaves, seeds, latex","Fresh fruit, leaf juice, seed powder","Papain, chymopapain, carpaine, benzyl glucosinolate","Avoid green papaya and latex in pregnancy — causes uterine contractions","Papaya leaf juice shown in clinical trials to increase platelet count in dengue fever","Tropical Americas, widely cultivated"),
    ("Pepper","Piper nigrum","Piperaceae","Maricha","Digestion, anti-inflammatory, antioxidant, respiratory, bioavailability enhancer","Fruit (berries)","Powder, decoction, fresh berries","Piperine, piperic acid, caryophyllene, limonene","Generally safe in food amounts; excess causes gastric irritation","Piperine increases bioavailability of curcumin by 2000% — key ingredient in Ayurvedic formulas","South India, widely cultivated tropically"),
    ("Pomegranate","Punica granatum","Lythraceae","Dadima","Heart health, anti-inflammatory, antioxidant, digestive, memory, blood pressure","Fruit, peel, bark, flowers","Fresh juice, peel decoction, flower infusion","Punicalagin, punicalin, ellagic acid, anthocyanins","Generally safe; may interact with blood pressure medications","Pomegranate juice has higher antioxidant activity than red wine and green tea","Iran, widely cultivated"),
    ("Raktachandini","Bixa orellana","Bixaceae","Sinduri","Antimicrobial, anti-inflammatory, fever, skin diseases, antioxidant","Seeds, leaves, bark","Seed paste, leaf infusion","Bixin, norbixin, tocotrienols, flavonoids","Generally safe; avoid in pregnancy in high doses","Seeds produce annatto — natural food colorant used globally as orange-yellow dye","Tropical Americas, cultivated in India"),
    ("Rose","Rosa centifolia","Rosaceae","Shatapatri","Digestive, anti-inflammatory, liver, mental health, skin care, vitamin C","Flowers, rose water, rose hip","Fresh petals, rose water, rose hip tea","Quercetin, kaempferol, catechins, vitamin C, tannins","Generally safe; some varieties cause allergic reactions","Rose hip contains 40x more Vitamin C than oranges — key in Chyawanprash formulation","Middle East, widely cultivated globally"),
    ("Sampige","Michelia champaca","Magnoliaceae","Champaka","Fever, skin diseases, anti-inflammatory, diuretic, wound healing","Flowers, bark, leaves","Flower infusion, bark decoction, leaf paste","Liriodenine, micheline, isoquercitrin, champacol","Generally safe; bark may be abortifacient in large doses","Sacred to Hindus and Buddhists — temple gardens always include champaka trees","South and Southeast Asia"),
    ("Snake_plant","Sansevieria trifasciata","Asparagaceae","Nagadamani","Air purifier, antibacterial, anti-inflammatory, wound healing","Leaves","Leaf juice, external paste","Saponins, flavonoids, phenolics, steroidal compounds","Mildly toxic if ingested — causes nausea and vomiting","One of NASA's top air-purifying plants — removes formaldehyde, benzene, and trichloroethylene","West Africa, widely cultivated as houseplant"),
    ("Tamarind","Tamarindus indica","Fabaceae","Amlika","Digestive health, laxative, fever, antibacterial, anti-inflammatory, liver","Fruit pulp, leaves, bark, seeds","Fresh pulp, decoction, candy","Tartaric acid, malic acid, citric acid, vitamin C, potassium","Generally safe; excess causes loose stools; high caloric content","Tamarind pulp has the highest natural tartaric acid content of any food plant","Tropical Africa, widely cultivated in India"),
    ("Taro","Colocasia esculenta","Araceae","Arbi","Digestive health, immune support, blood pressure, anti-inflammatory","Corm, leaves","Cooked corm, leaf decoction","Taro saponins, vitamin E and C, potassium, fiber","Raw taro contains calcium oxalate crystals — always cook thoroughly before eating","Taro has been a staple crop in Asia and Pacific for over 10000 years","Southeast Asia, widely cultivated"),
    ("Tecoma","Tecoma stans","Bignoniaceae","Piliya","Diabetes, anti-inflammatory, diuretic, antibacterial, digestive","Leaves, bark, flowers","Leaf decoction, bark infusion","Tecomine, tecostanine, skimmianine, boschniakine","Generally safe in therapeutic doses; avoid in pregnancy","Yellow flowers used in traditional Mexican and Indian medicine for diabetes since centuries","Tropical Americas, naturalized in India"),
    ("Thumbe","Leucas aspera","Lamiaceae","Dronapushpi","Fever, respiratory disorders, skin diseases, anti-inflammatory, insect bites","Whole plant, leaves, flowers","Fresh leaf juice, decoction, paste","Leucolactone, betulinic acid, oleanolic acid, ursolic acid","Generally safe in traditional doses","Flowers used as natural insect repellent in traditional Indian households","South Asia, Southeast Asia"),
    ("Tulsi","Ocimum tenuiflorum","Lamiaceae","Tulasi","Respiratory disorders, stress, fever, antibacterial, adaptogen, immunity booster","Leaves, seeds, roots, essential oil","10 fresh leaves chewed daily; decoction as tea","Eugenol, rosmarinic acid, ursolic acid, linalool, beta-caryophyllene","Safe; avoid large doses in pregnancy; may slow blood clotting","Queen of Ayurvedic herbs — one of the most studied medicinal plants with 300+ peer-reviewed studies","Tropical Asia, cultivated throughout India"),
    ("Turmeric","Curcuma longa","Zingiberaceae","Haridra","Anti-inflammatory, antioxidant, wound healing, liver support, joint pain, digestive","Rhizome","Powder in food, golden milk, paste, capsules","Curcumin, bisdemethoxycurcumin, ar-turmerone, turmerone","Safe in food doses; high supplement doses cause nausea; avoid with blood thinners","Subject of 12000+ peer-reviewed studies — most scientifically studied natural compound in history","South and Southeast Asia, widely cultivated"),
    ("Wood_sorrel","Oxalis corniculata","Oxalidaceae","Amrul","Digestive disorders, scurvy prevention, fever, skin diseases, antibacterial","Whole plant, leaves","Fresh leaves in food, leaf juice, paste","Oxalic acid, vitamin C, flavonoids, tannins","Excess causes kidney stones due to high oxalic acid; avoid in kidney disease","Ancient Romans used wood sorrel as a vitamin C source to prevent scurvy on long campaigns","Worldwide distribution — cosmopolitan weed"),
]

def run_migration():
    with engine.connect() as conn:
        # Create table
        conn.execute(text(CREATE_TABLE))
        conn.commit()
        print("Table created successfully")

        # Insert all plants with upsert
        for i, p in enumerate(PLANTS_DATA):
            conn.execute(text("""
                INSERT INTO plants (name, scientific_name, family, ayurvedic_name,
                    medicinal_uses, parts_used, preparation, active_compounds,
                    toxicity, description, habitat)
                VALUES (:name, :sci, :fam, :ayu, :med, :parts, :prep, :comp, :tox, :desc, :hab)
                ON CONFLICT (name) DO UPDATE SET
                    scientific_name = EXCLUDED.scientific_name,
                    medicinal_uses = EXCLUDED.medicinal_uses,
                    updated_at = NOW()
            """), {
                "name": p[0], "sci": p[1], "fam": p[2], "ayu": p[3],
                "med": p[4], "parts": p[5], "prep": p[6], "comp": p[7],
                "tox": p[8], "desc": p[9], "hab": p[10]
            })
        conn.commit()
        print(f"Seeded {len(PLANTS_DATA)} plants successfully")

if __name__ == "__main__":
    run_migration()
    print("Migration complete")
